### PR TITLE
Python 3.12

### LINKED ISSUE #3020: Retire wrap_socket from ssl and tests
Python 3.12 formally removes wrap_socket due to [CWE-295](https://cwe.mitre.org/data/definitions/295.html). Prior to rolling in 3.12, while deprecating 3.7 we need to solve this issue.

This change requires a release of redis-py 5.1.0, and dropping Python 3.7.

#2979

### PR DESCRIPTION
**Pull request by chayim**
Updating the trove, and CI to support the Python 3.12 release announcement.

closes #3020

### CODE REVIEW

**Comment by chayim** [comment]
https://github.com/MagicStack/uvloop/issues/567 is a precursor

**Comment by adamantike** [comment]
Today, `uvloop` released version 0.18.0, with support for Python 3.12, in case you want to retrigger the CI!

**Comment by foarsitter** [comment]
Any news on this PR?

**Comment by chayim** [comment]
Folks, I straight up forgot about this. We're getting it into the 5.1 beta with the removal of Python 3.7 too. @dvora-h leaving this with you.

**Comment by chayim** [comment]
@adamantike thanks, used that.. but have an SSL context issue within the asyncio side. Are you familiar with this at all?

**Comment by chayim** [comment]
Part of https://github.com/redis/hiredis-py/issues/167

**Comment by branchvincent** [comment]
fyi, 3.12 also [removes `distutils`](https://docs.python.org/3.12/whatsnew/3.12.html#removed) so this import will need to be replaced

https://github.com/redis/redis-py/blob/07fc339b4a4088c1ff052527685ebdde43dfc4be/redis/commands/graph/query_result.py#L3

**Review by vladvildanov — APPROVED** [review]

**Pull request merged**
