### PR TITLE
Response parsing occasionally fails to parse floats

### PR DESCRIPTION
**Pull request by chayim**
- filtering out codecov paths
- parse_to_list fails to parse float values

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Comment by chayim** [comment]
@bmerry Tagging you here given our other bug.  Is there any way I can test this specific change with your project?  I'm changing a helper underneath, but I realize it could expose a bug, if people assume that floats are strings. If not - I'm merge ready.

**Comment by bmerry** [comment]
I'm afraid I'm lacking some context. What is parse_to_list used for?

**Comment by bmerry** [comment]
>  Is there any way I can test this specific change with your project?

The project is [fakeredis](https://github.com/jamesls/fakeredis/), which implements a Connection subclass that pretends to be a Redis server. It hasn't kept up to date with all the new Redis protocol things, which is why tests have been failing when redis-py generates such protocol.

You can probably try running the fakeredis unit tests yourself. You should run them against a Redis 6.2.6 server (otherwise you'll get a bunch of failures for the stuff where it does emulate that version), and be aware that it will discard any data currently held by the server. Alternatively I think it'll skip the tests against the real redis server if it can't connect, and that'll make the tests twice as fast to run too.

**Comment by chayim** [comment]
> I'm afraid I'm lacking some context. What is parse_to_list used for?

I realise that this isn't something that you'd currently be using. It's part of the 4.0.0 module support. Apologies, I shouldn't have tagged you.

On the plus side, I've closed fakeredis, which is pretty fun. Thanks :D!

**Pull request merged**
