### PR TITLE
Async clusters: Support creating locks inside async functions

### PR DESCRIPTION
**Pull request by utkarshgupta137**
### Pull Request check-list

- [x] Does `$ tox` pass with this change (including linting)?
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

### Description of change

This allows creating the client at the module level or before the event loop has been initialized.
Ref: https://github.com/encode/starlette/issues/1315#issuecomment-1096256231

### CODE REVIEW

**Comment by utkarshgupta137** [comment]
@chayim @dvora-h This is a minor fix which should be included in 4.4.0. If it is still far away, I can raise a PR for the 4.3 branch as well.

**Comment by chayim** [comment]
@utkarshgupta137 We're still waiting on #2407 and given your fix.. I'm pretty good with this getting into 4.4 as that merge. Let's give a bit longer (end of week maybe) for [your PR in arq](https://github.com/samuelcolvin/arq/pull/366), and then we can merge it down + decide.

Does that work for you? I'd really like to **not** have multiple releases :D

**Comment by utkarshgupta137** [comment]
> @utkarshgupta137 We're still waiting on #2407 and given your fix.. I'm pretty good with this getting into 4.4 as that merge. Let's give a bit longer (end of week maybe) for [your PR in arq](https://github.com/samuelcolvin/arq/pull/366), and then we can merge it down + decide.
> 
> Does that work for you? I'd really like to **not** have multiple releases :D

Sure, it would work for me. But I don't think it is reasonable to wait for a third-party package to fix what is essentially a misuse (undefined behaviour) on their end. For all we know, there could be many other packages out there misusing some functionality of this package...
Also, there are other breaking changes in this release, so ideally, packages using redis as a dependency should have a version cap.

**Comment by chayim** [comment]
@utkarshgupta137 I randomly head out to the internet and contribute version caps for reasons like this. Part of a general goal of not breaking the community means I was happy to delay in this case, especially with the backport to 4.3.5.

Thanks again for the fix in arq - this goes into 4.4x.

**Review by chayim — APPROVED** [review]

**Pull request merged**
