### PR TITLE
Add support for new TDIGEST features and changes

### PR DESCRIPTION
**Pull request by dvora-h**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Review by shacharPash — APPROVED** [review]

**Comment by akx** [comment]
Just curious (as a contributor to redis-py):

* Why was "View Test Results" removed? That doesn't seem related to this PR's purpose.
  * Was the Codecov action removed on purpose at the same time? (It wasn't added by #2381.)
* Why isn't the PR checklist, or "Description of the change" filled out at all?

**Comment by dvora-h** [comment]
View Test Results removed because it failed the CI even when the tests passed and Codecov was accidentally removed.
Thanks for the attention!

**Comment by akx** [comment]
Hi @dvora-h – can you show where View Test Results was failing CI? All I can find in the previous Checks results here are some `async` tests being flaky (the same thing that is _currently_ failing CI in `master` and other PRs).

**Comment by dvora-h** [comment]
here:
https://github.com/redis/redis-py/actions/runs/3096152791/jobs/5011363907
https://github.com/redis/redis-py/actions/runs/3092245154/jobs/5003566392
The tests passed but the CI failed

**Pull request merged**
