### PR TITLE
Pyupgrade + flynt + f-strings

### PR DESCRIPTION
**Pull request by akx**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `$ tox` pass with this change (including linting)?
  - Seemed to – some tests were skipped though. 
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
  - See https://github.com/akx/redis-py/pull/1  
- [x] Is the new or changed code fully tested?
  - The changes are mechanical. 
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
  - No functional changes. 
- [x] Is there an example added to the examples folder (if applicable)?
  - No functional changes. 

### Description of change

Since redis-py is Python 3.6+, this PR runs `pyupgrade` and `flynt`, followed by some manual edits, to turn all `%` and (almost all) `.format()` invocations to f-strings instead.

`pyupgrade` also does a couple other things such as fixes up `super()` calls and refactors things to use dict comprehensions, etc.

This is tangentially related to #1734 (so heads-up @WisdomPill 😄). Since `black`'s code style prescribes a max-line-length of 88, I've (temporarily) adjusted the `flake8` invocation in CI for that.

### CODE REVIEW

**Comment by chayim** [comment]
Wow @akx thanks for introducing me to flynt.  What do you think of modifying the commit hooks / _tox linters_ call so that we fail immediately if there are any code chnages?  You'd have to add this to _dev_requirements.txt_ but this way we could catch PRs that violate this in the future.  WYDT?

**Comment by akx** [comment]
Sure thing @chayim! Added that configuration in e9008bc.

**Comment by WisdomPill** [comment]
great PR @akx!
Nice to see this new tool (flynt). 

Which PR are we going to merge first? @chayim

**Comment by chayim** [comment]
@akx didn't pass unfortunately.

@WisdomPill I'd like to merge this, then yours - only since yours is pure autogen on top.  I am feel guilty about pushing you again - please don't hate me! I think these are both _great_ contributions and will be very thankful when they land.

**Comment by akx** [comment]
@chayim Ah, I forgot that `flynt` wants the path to look at (whereas `flake8` and friends default to the cwd). Fixed... 

I also agree that this should probably be merged first, since there were a bunch of hand-rolled fixes in the 3rd commit.

**Comment by WisdomPill** [comment]
No problem, just let me know when this gets merged so I can rebase on top of it

**Comment by chayim** [comment]
:heart: to everyone here. This is a beautiful thing.

@WisdomPill by the time you receive this, it'll now be in. Hopefully (as in 30 minutes from now) master will also be versioned as 4.1.0rc2 so that we can close this off.  Yours is the next merge in.

**Pull request merged**
