### PR TITLE
Making search document subscriptable

### PR DESCRIPTION
**Pull request by aksinha334**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._
[Fixed issue #2598 - make Document class subscriptable]

### CODE REVIEW

**Comment by aksinha334** [comment]
Hi @dvora-h , any idea how to re-run the checks, I think it's failing for some other reason.

**Comment by aksinha334** [comment]
image

Checks are failing which is unrelated to PR changes.

@chayim , can you check this once.

**Comment by dvora-h** [comment]
@aksinha334 Thanks for contributing this feature! Can you please add a test for it?

**Comment by aksinha334** [comment]
image

Hi @dvora-h  @chayim , again check is failing on unrelated changes of PR, now failing in redis/asyncio/client.py line 463.

I've also added test of this PR. Can you please check for failure and review PR.

from redis.commands.search.result import Result  --> returns Document class, so I have simply did subscriptable on that.

Sorry for long commit, I had to rebase, still learning.

**Comment by aksinha334** [comment]
Hi @dvora-h , check has been passed. Can you please review the PR?

**Review by dvora-h — APPROVED** [review]

**Pull request merged**
