### PR TITLE
DOC add pipeline examples

### PR DESCRIPTION
**Pull request by Iglesys347**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

This PR relates to #1744 

I created a simple jupyter example of how to use pipelines with a performance comparison.

### CODE REVIEW

**Comment by chayim** [comment]
Hi @Iglesys347 this is awesome! Any chance you can add this, as a link in the examples.rst?

**Comment by Iglesys347** [comment]
Hi @chayim, I added the notebook to `example.rst` and I tested locally (with `invoke build-docs`) everything seems to work properly.

The CI fails due to an internal server error, I'll try to re-trigger it latter.

**Comment by Iglesys347** [comment]
All check passes 😄

**Review by dvora-h — APPROVED** [review]
@Iglesys347 Thank you for helping make our documentation better!

**Pull request merged**
