### PR TITLE
Adding support for WITHSCORE in zrank

### LINKED ISSUE #2689: Support ZRANK: Added the optional `WITHSCORE` argument.
Documented [here](https://redis.io/commands/ZRANK).

### PR DESCRIPTION
**Pull request by SoulPancake**
closes #2758
closes #2689

### CODE REVIEW

**Comment by chayim** [comment]
@SoulPancake I updated your code to fix the linter issue. Maybe take a stab at it from here?

**Comment by SoulPancake** [comment]
@chayim Can you take a look at this

**Comment by chayim** [comment]
LGTM @SoulPancake . Thank you for revisiting!

**Review by chayim — APPROVED** [review]

**Comment by uglide** [comment]
The PR title was misleading. I've updated it.

**Comment by chayim** [comment]
@dvora-h given #2758 being merged, maybe you can double-check this?

**Comment by dvora-h** [comment]
Closing as this is already merged in #2758.
(Sorry, @SoulPancake I missed it before I merged)

**Pull request closed without merging**
