### PR TITLE
Fix incorrect asserts in test and ensure connections are closed

### PR DESCRIPTION
**Pull request by kristjanvalur**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Do tests and lints pass with this change?
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [x] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

Various error message assertions were incorrectly placed and were not testing anything.
In addition, sockets were being leaked in the tests.

### CODE REVIEW

**Review by dvora-h — COMMENTED** [review]
Just to my understanding - why is this the correct way to test it?

**Comment by dvora-h** [comment]
@kristjanvalur I think you missed my question here, if you can, I would like to understand it.

**Comment by kristjanvalur** [comment]
> @kristjanvalur I think you missed my question here, if you can, I would like to understand it.

I did indeed, sorry :)

```python
with pytest.raises(ConnectionError) as e:
            sslclient.ping()
            assert "SSL: CERTIFICATE_VERIFY_FAILED" in str(e)
```
The above assert will never be hit.  sslclient.ping() raises a connection error and the `pytest.raises` context manager is exited, before execution ever gets to `assert`.
The correct way to examine the raised exception is to examine the contents of `e.value` _after_ exiting the context manager.  If just grepping for a string, then `str(e)` is good enough too. 

see https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=raises#pytest.raises

**Comment by kristjanvalur** [comment]
seems unit tests runners are shaky again.

**Review by dvora-h — APPROVED** [review]

**Pull request merged**
