### PR TITLE
Cherry-pick for 4.3.5

### PR DESCRIPTION
**Pull request by dvora-h**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Review by utkarshgupta137 — APPROVED** [review]

**Comment by utkarshgupta137** [comment]
Can you also include: https://github.com/redis/redis-py/pull/2439

**Comment by utkarshgupta137** [comment]
Also: https://github.com/redis/redis-py/pull/2231

**Comment by utkarshgupta137** [comment]
@dvora-h @chayim Any updates on this? I would love to finally start using this package in production...

**Comment by utkarshgupta137** [comment]
@dvora-h @chayim Can we please release this?

**Comment by chayim** [comment]
@utkarshgupta137 honestly... we really want to get 4.4.0 out there - but there's bug https://github.com/redis/redis-py/issues/2407 we could use a hand on. I don't want to introduce anything else - other than that bug, then we release it.

But, I've merged in the module changes, and unit test changes - as well as your bug request.. If it's all green, we can release this in the interim as well.

**Pull request merged**
