### PR TITLE
Fix dead weakref in sentinel connection causing ReferenceError (#2767)

### PR DESCRIPTION
**Pull request by shahar-lev**
### Pull Request check-list

- [x] Does `$ tox` pass with this change (including linting)?
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Is there an example added to the examples folder (if applicable)?
- [x] Was the change added to CHANGES file?

### Description of change

Instead of passing the sentinel connection a `weakref.proxy` to the sentinel connection pool, I pass it a wrapper object (of type `SentinelConnectionPoolProxy`) that holds a `weakref.ref` to the sentinel connection pool (and checks its liveness before invocation).
Please see related issue #2767

### CODE REVIEW

**Review by chayim — APPROVED** [review]

**Comment by chayim** [comment]
@shahar-lev kindly resolve the conflict, and we can include it in the next release

**Comment by shahar-lev** [comment]
@chayim pulled from master.

**Comment by shahar-lev** [comment]
@chayim do you need anything else from me?

**Comment by chayim** [comment]
Nope. We're good. It's just not yet merged. Will happen shortly.

**Pull request merged**
