### PR TITLE
Add CI action to install package from commit hash (#1781)

### PR DESCRIPTION
**Pull request by ashwani99**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change
- Resolves https://github.com/redis/redis-py/issues/1781
- Adding a CI action to `pip install` the package from current commit source

### CODE REVIEW

**Comment by chayim** [comment]
@ashwani99 awesome - this reproduces #1784 perfectly. I'll see what I can do to fix that.

**Comment by WisdomPill** [comment]
My two cents, I think this should be done for every version of python supported

**Comment by chayim** [comment]
@WisdomPill Now that we have this, I think it's fair. @ashwani99 mind trying to yank the python-version and add it to your matrix, in addition to updating the name for this test to reflect the matrix? Then, I think we have something amazing, test-wise.

**Comment by ashwani99** [comment]
@chayim sure, I will add the support for all python versions 3.6+

**Comment by chayim** [comment]
@ashwani99 For what it's worth, this was alerady useful. I used it to validate #1792 our collaboration on  the resulting change from #1784

**Comment by chayim** [comment]
Thanks @ashwani99! It has been such a pleasure. Merging as discussed in #1784

**Pull request merged**
