### PR TITLE
Made sync lock consistent and added types to it

### PR DESCRIPTION
**Pull request by WisdomPill**
Fixes: #1348
Needed for: jazzband/django-redis#603

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `$ tox` pass with this change (including linting)?
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Was the change added to CHANGES file?

### Description of change

Added blocking flag to client.lock and types to sync lock.
Some more nit picking inconsistency was fixed so that regardless on who the lock is used, all the options are the same.

If this is okay I will also add the same to the async version of the lock

### CODE REVIEW

**Comment by WisdomPill** [comment]
@chayim or @dvora-h friendly ping

**Comment by dvora-h** [comment]
Thanks @WisdomPill! It looks great to me! 

As you suggested - I would really appreciate if you add an async version as well

**Comment by WisdomPill** [comment]
nice! probably in the weekend I will be back at it :)

**Review by dvora-h — APPROVED** [review]

**Comment by WisdomPill** [comment]
sorry I did not finish working on the async version yet... I just started and got caught up by other things

**Comment by dvora-h** [comment]
@WisdomPill I want to merge this PR so please open another PR when you done with the async version, and feel free to let me know if you need help with it

**Comment by WisdomPill** [comment]
👍

**Pull request merged**
