### PR TITLE
Add py.typed in accordance with PEP-561

### PR DESCRIPTION
**Pull request by zmievsa**
### Pull Request check-list
- [x] Does `$ tox` pass with this change (including linting)?
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Is there an example added to the examples folder (if applicable)?
- [x] Was the change added to CHANGES file?

### Description of change

Add py.typed in accordance with PEP-561. Otherwise type checkers might ignore type hints from this package (particularly old versions of pyright)

### CODE REVIEW

**Comment by chayim** [comment]
@Ovsyanka83 thanks kindly! But.. the library isn't fully typed at this time. Want to help out by contributing type hints?

**Comment by Ovsyanka83** [comment]
Would love to. I think, the PEP allows us to specify that the typing is partial

**Comment by chayim** [comment]
Amazing, didn't know about the partial bit. Any idea how typeshed handles that? Those types are incorrect - but if they won't absorb (even after the 6 month cycle) it's... perhaps less valuable. WDYT?

**Comment by Ovsyanka83** [comment]
I will try to leave my full reply and research into that next week or, in the worst case, by the end of the month.

**Comment by akx** [comment]
@chayim We added types to Babel in the last release, see https://github.com/python-babel/babel/pull/975 and https://github.com/python/typeshed/pull/9832 for relevant discussion.

**Comment by chayim** [comment]
Thanks @akx any idea how partially typed works? typeshed is wrong in all sorts of places for redis-py... The library is only partially typed.. hence the Q

**Comment by akx** [comment]
@chayim I'd _assume_ that anything not explicitly typed will remain any-typed, just as if it hadn't been typed at all. But you'd probably not want to mix and match typeshed types with the native ones.

**Comment by chayim** [comment]
I have the same assumption.. hence my worry.  Maybe we should get this into 5 instead - along with more typings.

**Review by chayim — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
> typeshed is wrong in all sorts of places for redis-py

@chayim If you have concrete examples of this, please let the typeshed project know and we'll try to fix it.

Great to see redis-py adding py.typed though!

**Comment by Avasam** [comment]
(not a typeshed maintainer, just a contributor), FWIW, https://github.com/redis/redis-py/issues/2730 has been blocking me from fixing a handful of redis typing issues. And furthermore enabling more tools and checks in typeshed that ensures proper typing.

Concerning incomplete typing in both the base library (here) and typeshed, refer to my comment there: https://github.com/python/typeshed/issues/10592#issuecomment-1706972996 I fully support type definitions moving fully into Redis itself. But if it can't be done quickly or completely, Typeshed should be able to provide explicitly partial stubs and gradually remove modules as they are type-completed in Redis.

**Pull request merged**
