### PR TITLE
fix: workaround asyncio bug on connection reset by peer

### LINKED ISSUE #2237: IndexError on Connection Failure
**Version**: 
redis-py: `4.3.3`
Redis Version: `6.0.14`

**Platform**: 
- Kubernetes pod
- Docker image
- Python3.9

**Description**: 

We are seeing `IndexError` when we reboot a redis server and our async Redis connection is closed and reconnect happens. The IndexError is [located here](https://github.com/redis/redis-py/blob/bedf3c82a55b4b67eed93f686cb17e82f7ab19cd/redis/asyncio/connection.py#L765) in the codebase. 

Traceback is like this:

```python
  File "/usr/local/lib/python3.9/site-packages/sfdi_events_synd/clients/redis.py", line 81, in ping
    return await client.ping()
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/client.py", line 473, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/connection.py", line 1700, in get_connection
    await connection.connect()
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/connection.py", line 706, in connect
    raise ConnectionError(self._error_message(e))
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/connection.py", line 765, in _error_message
    f"Error {exception.args[0]} connecting to {self.host}:{self.port}. "
IndexError: tuple index out of range
```

It looks like our exception_args is empty?

```python
        if len(exception.args) == 1:
            return f"Error connecting to {self.host}:{self.port}. {exception.args[0]}."
        else:
            return (
                f"Error {exception.args[0]} connecting to {self.host}:{self.port}. "
                f"{exception.args[0]}."
            )
```

We have been experimenting with ConnectionPooling and reconnect strategies, and this came up this morning on an experimental attempt to drop connections and reconnect in code that looks _roughly_ like this:

```python
@asynccontextmanager
async def redis_connection(pool):
    """
    Context manager for automatically closing connections on finish
    """
    connection = redis.Redis(
        connection_pool=pool, auto_close_connection_pool=False
    )
    yield connection
    await connection.close()


async def ping(pool):
    async with redis_connection(pool) as client:
        return await client.ping()
```

As noted above, we run this while rebooting our server to see if we can simulate failing connections and reconnect. We were expecting to see a `ConnectionError` instead of an `IndexError`.

### PR DESCRIPTION
**Pull request by sileht**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `$ tox` pass with this change (including linting)?
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Is there an example added to the examples folder (if applicable)?
- [x] Was the change added to CHANGES file?

### Description of change

fix: workaround asyncio bug on connection reset by peer

Fixes #2237

### CODE REVIEW

**Comment by sileht** [comment]
@chayim @dvora-h can you take a look at this? 🙏

**Review by dvora-h — APPROVED** [review]

**Comment by sileht** [comment]
I'm curious what the process is to get a patch merged and released? Anything I can help with?

**Comment by dvora-h** [comment]
I'm merging it now, we will release a new version later this week / next week

**Comment by sileht** [comment]
Great, thank a lot.

**Comment by cancan101** [comment]
question on this fix, was there no value in raising the `ConnectionError` `from e`:
```python
except OSError as e:
    raise ConnectionError(self._error_message(e)) from e
```
to provide the underlying exception? At present the exception is lost beyond what is string formatted.  I am trying to track down what is going on here: https://github.com/redis/redis-py/issues/2406#issuecomment-1472861856

**Pull request merged**
