### PR TITLE
Fixing #issue2592 - Assigning step_count value 1 if it's 0 when passing in range function

### PR DESCRIPTION
**Pull request by aksinha334**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._
Fixing #2592 , assigning step_count value to 1 if it was 0 when passing in range function

### CODE REVIEW

**Comment by aksinha334** [comment]
Hi, @dvora-h @shacharPash, I have added the test and the check is passing, can you please review the PR?

I've just added the code to make sure [range](https://docs.python.org/3/library/functions.html#func-range) builtin function's parameter step is not 0. so making it 1 when it's 0.

**Comment by shacharPash** [comment]
Hey @aksinha334, Maybe try adding the code sample from the issue to the tests to show that the issue has been resolved

**Comment by aksinha334** [comment]
Hi @shacharPash ,

I've created the container using "invoke devenv", and using port 16379 for cluster mode, but when I'm running the code, it's throwing the below error 
`redis.exceptions.RedisClusterException: No way to dispatch this command to Redis Cluster. Missing key.
You can execute the command by specifying target nodes.
Command: ('CLIENT TRACKING', 'ON', 'REDIRECT', 51, 'PREFIX', 'foo', 'BCAST')`

sorry, I searched on the internet but didn't get any solution, do you have any idea or link about the **missing key** error so I can proceed further? any help will be great as I'm new to this codebase.

A snippet of code:
`

    client1 = cluster.RedisCluster.from_url('redis://localhost:16379/0')
    id = client1.client_id()

    pubsub = client1.pubsub()
    pubsub.subscribe(**{'__redis__:invalidate': handler})
    pubsub.run_in_thread(daemon=True, sleep_time=None)

    client1.client_tracking_on(clientid=id, prefix=['foo'], bcast=True)

    client1.get('fooASF')
    for i in range(10):
        client1.set('fooASF', '23423423ff')

    time.sleep(100)
`

**Comment by matejsp** [comment]
@aksinha334 did you manage to setup the setup a working test?

**Pull request closed without merging**
