### PR TITLE
Add set and get examples

### LINKED ISSUE #1744: We need examples!
In order to help drive adoption, and make it easier for others to get started with redis-py, I'd love to start including examples with the repository. Recently, I [introduced a change](https://github.com/redis/redis-py/pull/1743) to start splitting up the documentation - as a first step - which will be part of 4.1.0.

Next - I plan on adding support for [jupyter notebooks](https://docs.readthedocs.io/en/stable/guides/jupyter.html) in our documentation to enable this.

### PR DESCRIPTION
**Pull request by dogukanteber**
This PR partly resolves #1744. I have added simple get and set examples according to [this comment](https://github.com/redis/redis-py/issues/1744#issuecomment-983925617)

### CODE REVIEW

**Comment by chayim** [comment]
@dogukanteber This is great - exactly the sorts of things we were discussing in the PR. What do you think about adding the link to the examples.rst in the docs folder? Can I trouble you to connect the dots. After that, we'll merge right in!.

**Comment by dogukanteber** [comment]
Oh, I completely forgot about that part @chayim. I linked the file to example.rst

**Comment by chayim** [comment]
@dogukanteber This is perfect! Unit tests are failing due to an upstream docker issue that I need to fix. This is solidly approved - I'll merge once I have that docker fixed. So excited!!!!

**Review by chayim — APPROVED** [review]
Approved - needs the same redismod upstream docker fix as other PRs. This is on me.

**Pull request merged**
