### PR TITLE
Adding links to redis documents in function calls

### LINKED ISSUE #1712: Link commands to redis commands
Currently, the commands in redis-py (core, etc) have command definitions, and docstrings, but it would be great, if we could add links to the individual redis command documentation, on redis.io.

This is a lot of work!

### PR DESCRIPTION
**Pull request by Carlosbogo**
Added links to the documentation in the docstrings in redis/commands/core.py

closes #1712

### CODE REVIEW

**Comment by chayim** [comment]
@Carlosbogo Awesome! Now - there are flake8 formatting errors, [here](https://github.com/redis/redis-py/runs/4231586572?check_suite_focus=true).  To fix anything with lines that are too long simply add a '  # noqa' (without the quotes) to the end of the associated line.

This would ideally be solved by #1644 anyways.

**Comment by chayim** [comment]
@Carlosbogo We are so close. There are two flake8 errors left:
```
./redis/commands/core.py:2187:1: W293 blank line contains whitespace
./redis/commands/core.py:2195:1: W293 blank line contains whitespace
```

If you can eliminate those (and other flakes), I'll pull this into whichever release this lines up with, 4.0.2 or 4.1.0.

If it helps - you can test locally prior to pushing by:

1. _pip install flake8_ (I'm assuming you have a virtualenv) or _pip install --user flake8_

**Comment by Carlosbogo** [comment]
Thank you for the advice, that will definitely help a lot in the future!

**Comment by chayim** [comment]
Well this is just *awesome*. Thank you so much @Carlosbogo for making these changes. I'm going to add it into the upcoming (4.0.2) release. So that we can roll this out tomorrow. :clap:

**Pull request merged**
