### PR TITLE
tox.ini: get rid of typoed healthcheck stanzas

### PR DESCRIPTION
**Pull request by akx**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `$ tox` pass with this change (including linting)?
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?
  - I don't think it's necessary in this case.

### Description of change

Since the actual configuration should be `healthcheck_cmd`, there's probably no good reason to keep no-op configuration in tox.ini.

Closes #2395 (alternate take)

### CODE REVIEW

**Comment by akx** [comment]
In light of #2390, this is probably not a good idea.

**Comment by akx** [comment]
@chayim Want to take a look at this? You seem to have initially added these in 63ebe693...

**Comment by akx** [comment]
Friendly ping, @chayim :)

**Comment by dvora-h** [comment]
Not relevant anymore (see #2793)

**Pull request closed without merging**
